import {
  antipattern as effectAntipattern,
  correctness as effectCorrectness,
  effectNative,
  style as effectStyle,
} from "@effect/tsgo/oxlint-presets";
import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";
import vitest from "ultracite/oxlint/vitest";

const asErrors = (rules: Iterable<string>) =>
  Object.fromEntries(Array.from(rules, (rule) => [rule, "error"] as const));

const productionTypeAwareRules = [
  "typescript/consistent-return",
  "typescript/no-array-delete",
  "typescript/no-deprecated",
  "typescript/no-unsafe-argument",
  "typescript/no-unsafe-assignment",
  "typescript/no-unsafe-call",
  "typescript/no-unsafe-member-access",
  "typescript/no-unsafe-return",
  "typescript/no-unsafe-type-assertion",
  "typescript/restrict-plus-operands",
  "typescript/restrict-template-expressions",
  "typescript/strict-boolean-expressions",
  "typescript/switch-exhaustiveness-check",
  "typescript/unbound-method",
] as const;

const universalTypeAwareRules = [
  "typescript/await-thenable",
  "typescript/no-floating-promises",
  "typescript/no-misused-promises",
  "typescript/only-throw-error",
] as const;

export default defineConfig({
  extends: [
    core,
    react,
    tanstack,
    vitest,
    effectCorrectness,
    effectAntipattern,
    effectNative,
    effectStyle,
  ],
  ignorePatterns: [...(core.ignorePatterns ?? []), "migrations/**"],
  overrides: [
    {
      files: ["src/**/*.{ts,tsx}", "alchemy.run.ts", "vite.config.ts"],
      rules: {
        ...asErrors(Object.keys(effectAntipattern.rules ?? {})),
        ...asErrors(Object.keys(effectNative.rules ?? {})),
        ...asErrors(productionTypeAwareRules),
        "effecttsgo/deterministic-keys": "error",
        "effecttsgo/missing-effect-service-dependency": "error",
        "effecttsgo/nested-effect-gen-yield": "error",
        "effecttsgo/service-not-as-class": "error",
        "effecttsgo/strict-boolean-expressions": "error",
      },
    },
    {
      files: [
        "src/{modules,apps,platform,shared}/**/*.{ts,tsx}",
        "tests/{modules,apps,platform,shared}/**/*.{ts,tsx}",
      ],
      rules: {
        "unicorn/filename-case": "off",
      },
    },
    {
      files: ["tests/**/*.{ts,tsx}"],
      rules: {
        "effecttsgo/async-function": "off",
        "effecttsgo/crypto-random-uuid": "off",
        "effecttsgo/global-console": "off",
        "effecttsgo/global-date": "off",
        "effecttsgo/global-random": "off",
        "effecttsgo/global-timers": "off",
        "effecttsgo/new-promise": "off",
        "effecttsgo/node-builtin-import": "off",
        "effecttsgo/process-env": "off",
      },
    },
    {
      files: ["scripts/**/*.ts"],
      rules: {
        "effecttsgo/async-function": "off",
        "effecttsgo/global-console": "off",
        "effecttsgo/new-promise": "off",
        "effecttsgo/node-builtin-import": "off",
        "effecttsgo/process-env": "off",
        "no-await-in-loop": "off",
      },
    },
  ],
  rules: {
    ...asErrors(Object.keys(effectCorrectness.rules ?? {})),
    "func-names": "off",
    "func-style": "off",
    "no-nested-ternary": "off",
    "no-use-before-define": "off",
    "no-void": "off",
    "react/hook-use-state": "off",
    "sort-keys": "off",
    "typescript/await-thenable": "off",
    "typescript/consistent-return": "off",
    "typescript/consistent-type-exports": "off",
    "typescript/dot-notation": "off",
    "typescript/no-array-delete": "off",
    "typescript/no-base-to-string": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-duplicate-type-constituents": "off",
    "typescript/no-floating-promises": "off",
    "typescript/no-for-in-array": "off",
    "typescript/no-implied-eval": "off",
    "typescript/no-meaningless-void-operator": "off",
    "typescript/no-misused-promises": "off",
    "typescript/no-misused-spread": "off",
    "typescript/no-mixed-enums": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-boolean-literal-compare": "off",
    "typescript/no-unnecessary-condition": "off",
    "typescript/no-unnecessary-qualifier": "off",
    "typescript/no-unnecessary-template-expression": "off",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unnecessary-type-conversion": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "off",
    "typescript/no-unsafe-enum-comparison": "off",
    "typescript/no-unsafe-member-access": "off",
    "typescript/no-unsafe-return": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unsafe-unary-minus": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/only-throw-error": "off",
    "typescript/prefer-find": "off",
    "typescript/prefer-includes": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-optional-chain": "off",
    "typescript/prefer-promise-reject-errors": "off",
    "typescript/prefer-readonly": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "off",
    "typescript/prefer-regexp-exec": "off",
    "typescript/prefer-return-this-type": "off",
    "typescript/prefer-string-starts-ends-with": "off",
    "typescript/promise-function-async": "off",
    "typescript/related-getter-setter-pairs": "off",
    "typescript/require-array-sort-compare": "off",
    "typescript/require-await": "off",
    "typescript/restrict-plus-operands": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/return-await": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/unbound-method": "off",
    "typescript/use-unknown-in-catch-callback-variable": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-nested-ternary": "off",
    ...asErrors(universalTypeAwareRules),
  },
});
