insert or ignore into auth_permission_definition (
  id,
  description,
  scope_type_present,
  scope_type,
  created_at,
  updated_at
) values
  ('mailbox.read', 'Read a mailbox', 1, 'mailbox', 0, 0),
  ('mailbox.modify', 'Modify mailbox content', 1, 'mailbox', 0, 0),
  ('mailbox.send', 'Send mail from a mailbox', 1, 'mailbox', 0, 0),
  ('mailbox.manage_settings', 'Manage mailbox settings', 1, 'mailbox', 0, 0),
  ('mailbox.manage_members', 'Manage mailbox members', 1, 'mailbox', 0, 0),
  ('folder.read', 'Read a folder', 1, 'folder', 0, 0),
  ('folder.modify', 'Modify a folder', 1, 'folder', 0, 0),
  ('message.read', 'Read mailbox messages', 1, 'mailbox', 0, 0),
  ('message.modify', 'Modify mailbox messages', 1, 'mailbox', 0, 0),
  ('draft.create', 'Create and edit drafts', 1, 'mailbox', 0, 0),
  ('draft.send', 'Send mailbox drafts', 1, 'mailbox', 0, 0),
  ('rule.manage', 'Manage mailbox rules', 1, 'mailbox', 0, 0),
  ('attachment.read', 'Read mailbox attachments', 1, 'mailbox', 0, 0),
  ('attachment.upload', 'Upload mailbox attachments', 1, 'mailbox', 0, 0),
  ('mailbox.export', 'Export mailbox data', 1, 'mailbox', 0, 0);

insert or ignore into auth_role_definition (
  id,
  description,
  created_at,
  updated_at
) values
  ('owner', 'Full mailbox control', 0, 0),
  ('manager', 'Manage mailbox content, rules, and sending', 0, 0),
  ('editor', 'Read and organize content and create drafts', 0, 0),
  ('viewer', 'Read allowed mailbox or folder content', 0, 0);

insert or ignore into auth_role_permission (
  role_id,
  permission_id,
  scope_type_present,
  scope_type
) values
  ('owner', 'mailbox.read', 1, 'mailbox'),
  ('owner', 'mailbox.modify', 1, 'mailbox'),
  ('owner', 'mailbox.send', 1, 'mailbox'),
  ('owner', 'mailbox.manage_settings', 1, 'mailbox'),
  ('owner', 'mailbox.manage_members', 1, 'mailbox'),
  ('owner', 'folder.read', 1, 'folder'),
  ('owner', 'folder.modify', 1, 'folder'),
  ('owner', 'message.read', 1, 'mailbox'),
  ('owner', 'message.modify', 1, 'mailbox'),
  ('owner', 'draft.create', 1, 'mailbox'),
  ('owner', 'draft.send', 1, 'mailbox'),
  ('owner', 'rule.manage', 1, 'mailbox'),
  ('owner', 'attachment.read', 1, 'mailbox'),
  ('owner', 'attachment.upload', 1, 'mailbox'),
  ('owner', 'mailbox.export', 1, 'mailbox'),
  ('manager', 'mailbox.read', 1, 'mailbox'),
  ('manager', 'mailbox.modify', 1, 'mailbox'),
  ('manager', 'mailbox.send', 1, 'mailbox'),
  ('manager', 'folder.read', 1, 'folder'),
  ('manager', 'folder.modify', 1, 'folder'),
  ('manager', 'message.read', 1, 'mailbox'),
  ('manager', 'message.modify', 1, 'mailbox'),
  ('manager', 'draft.create', 1, 'mailbox'),
  ('manager', 'draft.send', 1, 'mailbox'),
  ('manager', 'rule.manage', 1, 'mailbox'),
  ('manager', 'attachment.read', 1, 'mailbox'),
  ('manager', 'attachment.upload', 1, 'mailbox'),
  ('editor', 'mailbox.read', 1, 'mailbox'),
  ('editor', 'mailbox.modify', 1, 'mailbox'),
  ('editor', 'folder.read', 1, 'folder'),
  ('editor', 'folder.modify', 1, 'folder'),
  ('editor', 'message.read', 1, 'mailbox'),
  ('editor', 'message.modify', 1, 'mailbox'),
  ('editor', 'draft.create', 1, 'mailbox'),
  ('editor', 'attachment.read', 1, 'mailbox'),
  ('editor', 'attachment.upload', 1, 'mailbox'),
  ('viewer', 'mailbox.read', 1, 'mailbox'),
  ('viewer', 'folder.read', 1, 'folder'),
  ('viewer', 'message.read', 1, 'mailbox'),
  ('viewer', 'attachment.read', 1, 'mailbox');
