/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSplatRouteImport } from './routes/auth/$'
import { Route as AuthCompletePasswordResetRouteImport } from './routes/auth-complete/password-reset'
import { Route as AuthCompleteMagicLinkRouteImport } from './routes/auth-complete/magic-link'
import { Route as AuthCompleteEmailVerificationRouteImport } from './routes/auth-complete/email-verification'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompletePasswordResetRoute =
  AuthCompletePasswordResetRouteImport.update({
    id: '/auth-complete/password-reset',
    path: '/auth-complete/password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCompleteMagicLinkRoute = AuthCompleteMagicLinkRouteImport.update({
  id: '/auth-complete/magic-link',
  path: '/auth-complete/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteEmailVerificationRoute =
  AuthCompleteEmailVerificationRouteImport.update({
    id: '/auth-complete/email-verification',
    path: '/auth-complete/email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCompleteEmailVerificationRoute: typeof AuthCompleteEmailVerificationRoute
  AuthCompleteMagicLinkRoute: typeof AuthCompleteMagicLinkRoute
  AuthCompletePasswordResetRoute: typeof AuthCompletePasswordResetRoute
  AuthSplatRoute: typeof AuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/password-reset': {
      id: '/auth-complete/password-reset'
      path: '/auth-complete/password-reset'
      fullPath: '/auth-complete/password-reset'
      preLoaderRoute: typeof AuthCompletePasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/magic-link': {
      id: '/auth-complete/magic-link'
      path: '/auth-complete/magic-link'
      fullPath: '/auth-complete/magic-link'
      preLoaderRoute: typeof AuthCompleteMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/email-verification': {
      id: '/auth-complete/email-verification'
      path: '/auth-complete/email-verification'
      fullPath: '/auth-complete/email-verification'
      preLoaderRoute: typeof AuthCompleteEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCompleteEmailVerificationRoute: AuthCompleteEmailVerificationRoute,
  AuthCompleteMagicLinkRoute: AuthCompleteMagicLinkRoute,
  AuthCompletePasswordResetRoute: AuthCompletePasswordResetRoute,
  AuthSplatRoute: AuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
