/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DevEmailInboxRouteImport } from './routes/dev-email-inbox'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSplatRouteImport } from './routes/auth/$'
import { Route as AuthCompletePasswordResetRouteImport } from './routes/auth-complete/password-reset'
import { Route as AuthCompleteMagicLinkRouteImport } from './routes/auth-complete/magic-link'
import { Route as AuthCompleteEmailVerificationRouteImport } from './routes/auth-complete/email-verification'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMailboxesMailboxIdMessagesMessageIdHtmlRouteImport } from './routes/api/mailboxes/$mailboxId/messages/$messageId/html'
import { Route as ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRouteImport } from './routes/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'

const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevEmailInboxRoute = DevEmailInboxRouteImport.update({
  id: '/dev-email-inbox',
  path: '/dev-email-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompletePasswordResetRoute =
  AuthCompletePasswordResetRouteImport.update({
    id: '/auth-complete/password-reset',
    path: '/auth-complete/password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCompleteMagicLinkRoute = AuthCompleteMagicLinkRouteImport.update({
  id: '/auth-complete/magic-link',
  path: '/auth-complete/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteEmailVerificationRoute =
  AuthCompleteEmailVerificationRouteImport.update({
    id: '/auth-complete/email-verification',
    path: '/auth-complete/email-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute =
  ApiMailboxesMailboxIdMessagesMessageIdHtmlRouteImport.update({
    id: '/api/mailboxes/$mailboxId/messages/$messageId/html',
    path: '/api/mailboxes/$mailboxId/messages/$messageId/html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute =
  ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRouteImport.update(
    {
      id: '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline',
      path: '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-email-inbox': typeof DevEmailInboxRoute
  '/inbox': typeof InboxRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/html': typeof ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline': typeof ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-email-inbox': typeof DevEmailInboxRoute
  '/inbox': typeof InboxRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/html': typeof ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline': typeof ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-email-inbox': typeof DevEmailInboxRoute
  '/inbox': typeof InboxRoute
  '/api/health': typeof ApiHealthRoute
  '/auth-complete/email-verification': typeof AuthCompleteEmailVerificationRoute
  '/auth-complete/magic-link': typeof AuthCompleteMagicLinkRoute
  '/auth-complete/password-reset': typeof AuthCompletePasswordResetRoute
  '/auth/$': typeof AuthSplatRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/html': typeof ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute
  '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline': typeof ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-email-inbox'
    | '/inbox'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
    | '/api/mailboxes/$mailboxId/messages/$messageId/html'
    | '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-email-inbox'
    | '/inbox'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
    | '/api/mailboxes/$mailboxId/messages/$messageId/html'
    | '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
  id:
    | '__root__'
    | '/'
    | '/dev-email-inbox'
    | '/inbox'
    | '/api/health'
    | '/auth-complete/email-verification'
    | '/auth-complete/magic-link'
    | '/auth-complete/password-reset'
    | '/auth/$'
    | '/api/mailboxes/$mailboxId/messages/$messageId/html'
    | '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevEmailInboxRoute: typeof DevEmailInboxRoute
  InboxRoute: typeof InboxRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCompleteEmailVerificationRoute: typeof AuthCompleteEmailVerificationRoute
  AuthCompleteMagicLinkRoute: typeof AuthCompleteMagicLinkRoute
  AuthCompletePasswordResetRoute: typeof AuthCompletePasswordResetRoute
  AuthSplatRoute: typeof AuthSplatRoute
  ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute: typeof ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute
  ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute: typeof ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-email-inbox': {
      id: '/dev-email-inbox'
      path: '/dev-email-inbox'
      fullPath: '/dev-email-inbox'
      preLoaderRoute: typeof DevEmailInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/password-reset': {
      id: '/auth-complete/password-reset'
      path: '/auth-complete/password-reset'
      fullPath: '/auth-complete/password-reset'
      preLoaderRoute: typeof AuthCompletePasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/magic-link': {
      id: '/auth-complete/magic-link'
      path: '/auth-complete/magic-link'
      fullPath: '/auth-complete/magic-link'
      preLoaderRoute: typeof AuthCompleteMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-complete/email-verification': {
      id: '/auth-complete/email-verification'
      path: '/auth-complete/email-verification'
      fullPath: '/auth-complete/email-verification'
      preLoaderRoute: typeof AuthCompleteEmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mailboxes/$mailboxId/messages/$messageId/html': {
      id: '/api/mailboxes/$mailboxId/messages/$messageId/html'
      path: '/api/mailboxes/$mailboxId/messages/$messageId/html'
      fullPath: '/api/mailboxes/$mailboxId/messages/$messageId/html'
      preLoaderRoute: typeof ApiMailboxesMailboxIdMessagesMessageIdHtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline': {
      id: '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
      path: '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
      fullPath: '/api/mailboxes/$mailboxId/messages/$messageId/attachments/$attachmentId/inline'
      preLoaderRoute: typeof ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevEmailInboxRoute: DevEmailInboxRoute,
  InboxRoute: InboxRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCompleteEmailVerificationRoute: AuthCompleteEmailVerificationRoute,
  AuthCompleteMagicLinkRoute: AuthCompleteMagicLinkRoute,
  AuthCompletePasswordResetRoute: AuthCompletePasswordResetRoute,
  AuthSplatRoute: AuthSplatRoute,
  ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute:
    ApiMailboxesMailboxIdMessagesMessageIdHtmlRoute,
  ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute:
    ApiMailboxesMailboxIdMessagesMessageIdAttachmentsAttachmentIdInlineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
